### PR TITLE
Reusable heading

### LINKED ISSUE #19: Create Reusable Heading Component
Need a Reusable heading component that contains all options in the design like ( Font-size, colors, transform, font-style, etc... )

### PR DESCRIPTION
**Pull request by saifaldin**
### Initial Reusable Heading Component:

**Description**

- Created a reusable heading component, covering all heading variations on the webpage.

**What I Used**

- classnames package
  so you will need to run yarn when you test or pull master after merge

- tailwind.css classes for styling
but added some custom classes until finishing tailwind configuration PR

**How to Use It**

- first import the component and variants object:
`import {Heading, HEADING_OPTIONS} from ' _relative path_ '`

- Use the property `as` to specify the heading tag:
like `as = 'h1' ` , `as = 'h2'`, and so on. 
`as` is set to `p` by default.

- Any Heading in the webpage has one of four font-sizes:
1. `HEADING_OPTIONS.FONT_SIZES.XSMALL` = `1.5rem`
2.  `HEADING_OPTIONS.FONT_SIZES.SMALL` = `1.875rem`
3. `HEADING_OPTIONS.FONT_SIZES.MEDIUM` = `3.125rem`
4. `HEADING_OPTIONS.FONT_SIZES.LARGE` = `6.25rem`
Set the property `fontSize` to desired size, as in `fontSize={HEADING_OPTIONS.FONT_SIZES.MEDIUM}` to apply it.
`fontSize` is set to `HEADING_OPTIONS.FONT_SIZES.MEDIUM` by default.

- Any Heading in the webpage has one of two colors:
1. `HEADING_OPTIONS.COLOR.PRIMARY` = `#141f32` in global styling //blackish
2. `HEADING_OPTIONS.COLOR.SECONDARY` = `#f9320c4` in global styling // reddish
Set the property `color` to desired color, as in `color={HEADING_OPTIONS.COLOR.SECONDARY}` to apply it.
`color` is set to `HEADING_OPTIONS.COLOR.PRIMARY` by default.

- Headings here either have a line height of `4.375rem`, or none. So, if you need line height, just set `hasLineHeight={true}`

### CODE REVIEW

**Review by Nilegfx — DISMISSED** [review]
a good candidate for code review.

**Review by MAlngaawy — CHANGES_REQUESTED** [review]
I think you accidentally merged the two PRs together

please separate the two PRs
each one should have a clone from the master without the other pr

**Review by amagdy46 — APPROVED** [review]
LGTM!

**Review by MAlngaawy — APPROVED** [review]
LGTM

**Pull request merged**
