### PR TITLE
Api navigation

### PR DESCRIPTION
**Pull request by MustafaMadkour**
# Navigation Links API
## _Description_
 API to create navigation bar links and retrieve them from a mongodb database.
this is the first update to be compatible with the JSON server db. 

### Stack:
We used Nestjs - in typescript -and Mongodb as a databases.

### Request Body:
```````
{
    "links": [
        { "title": "link1", "url": "/link1" },
        { "title": "link2", "url": "/link2" }
    ],
    "downloadbtn": "downloadbtn url" 
}
```````

### Requests:  
we have these requests available:
- POST `localhost:3000/navigation` to create a new navigation link
- GET `localhost:3000/navigation/:id` to get a navigation link by its id

### Tasks to complete:
- [x] Navigation-Endpoints to db
- [x] Error Handler
- [x] Error Logger

### CODE REVIEW

**Comment by MustafaMadkour** [comment]
MONGO_URI='mongodb+srv://mustafa:mmmkkkmmm@cluster0.zj3wa.mongodb.net/prsresume?retryWrites=true&w=majority'

**Review by amagdy46 — APPROVED** [review]
LGTM!

**Comment by MustafaMadkour** [comment]
MONGO_URI='mongodb+srv://mustafa:mmmkkkmmm@cluster0.zj3wa.mongodb.net/prsresume?retryWrites=true&w=majority'

**Review by Nilegfx — CHANGES_REQUESTED** [review]
The navigation resource should be reconsidered, frontend shouldn't ask for specific documents to get the navigation, navigation-links or navigations or links (whatever the name of the resource) should be a list of (navigation links) each have title and description and url. 

the way we implemented it in json-server (single type) is NOT correct, I know you were trying to replicate it, but I originally made it list of links, not sure what was the reason behind converting it to single document and couple it with the download CV button, this is NOT correct at all. the CV button could appear anywhere in the design, doesn't necessarily relate to the navigation, having it in the navigation resources messes up with the navigation model, as you can see it forced you to change it from list of documents (which is correct) to single resource by id.

I was under impression that this should be what you both (backend and frontend) discussed in the meeting I mentioned (model alingmenet). 

please consider splitting the download button and the navigation link in separate resources or even hardcode the download CV button in the frontend and let the navigation links follows the restful standards.

**Pull request closed without merging**
