### PR TITLE
Features / scroll top & clip path shape

### PR DESCRIPTION
**Pull request by MAlngaawy**
**What I did** 
- Create a scroll top function to use at the footer button
- Simulate the shape at the section header at the design by using the clip-path

### CODE REVIEW

**Review by abdelrhmanali29 — CHANGES_REQUESTED** [review]
line width must be same in all the line look at design

**Review by abdelrhmanali29 — CHANGES_REQUESTED** [review]
set the transform smooth

**Review by abdelrhmanali29 — COMMENTED** [review]
set transition to take more time on scrolling

**Comment by MAlngaawy** [comment]
> set transition to take more time on scrolling

this is just a function that uses the `window.scrollTop` property

**Review by abdelrhmanali29 — APPROVED** [review]
LGTM

**Pull request merged**
